query BuscarSolicitacoesDeGarcom($idRestaurante: String!) {
    solicitacoes(
        idRestaurante: $idRestaurante
        ordenarPor: {
            criadoEm: desc
        }
        limit: 60
    ) {
        _id
        mesa
        criadoEm
        lido
    }
}