mutation CriarConta($entrada: EntradaDeConta!) {
  criarConta(entrada: $entrada) {
    token
    conta {
      _id
      dono {
        _id
        nome
      }
      lojas {
        _id
      }
    }
  }
}